[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'tpope/vim-rails'

[[plugins]]
repo = 'Keithbsmiley/rspec.vim'

[[plugins]]
repo = 'soramugi/auto-ctags.vim'

[[plugins]]
repo = 'janko/vim-test'

[[plugins]]
repo = 'tpope/vim-dispatch'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'othree/yajs.vim'

[[plugins]]
repo = 'vim-jp/vim-cpp'

[[plugins]]
repo = 'Shougo/deol.nvim'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'slim-template/vim-slim'

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'kana/vim-operator-replace'

[[plugins]]
repo = 'Shougo/neocomplete.vim'
if   = '''has('lua')'''

[[plugins]]
repo = 'Shougo/neosnippet'
if   = '''has('lua')'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
if   = '''has('lua')'''

[[plugins]]
repo = 'cespare/vim-toml'

# fzfの導入
[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'

[[plugins]]
repo = 'junegunn/fzf.vim'

[[plugins]]
repo = 'dag/vim-fish'
