[[plugins]]
repo = 'cohama/lexima.vim'
on_event = 'InsertEnter'
hook_post_source = '''
  " lexima.vimはInsertEnterのタイミングでマッピングを上書きするため、自分の設定で上書きしたい場合はそれより後に行う。
  " lexima.vimがマッピングを上書きするのを待ってから上書くため、timerを利用する。
  call timer_start(100, { -> my_settings#mappings#define_cr_for_insert_mode() })
'''

[[plugins]]
repo = 'sillybun/vim-repl'
on_cmd = ['REPLToggle']
hook_add = '''
  let g:sendtorepl_invoke_key = "!"
  let g:repl_console_name = 'REPL'
  let g:repl_program = {
    \ 'scheme': 'scheme',
    \ 'ruby': 'irb',
    \ 'default': 'fish',
  \}
  let g:repl_exit_commands = {
    \ 'scheme': '(quit)',
    \ 'ruby': 'exit',
    \ 'fish': 'exit',
  \}
'''

[[plugins]]
# .local.vimrcでg:dbにDBのURLを登録すると`DB`コマンドにURLを渡さなくてよくなる
repo = 'tpope/vim-dadbod'
on_cmd = ['DB']
