#!/bin/sh

# https://github.com/sugilog/dotfiles/blob/master/git-template/hooks/prepare-commit-msg
function _author_name() {
  if [ -n "${GIT_AUTHOR_NAME}" ]; then
    echo ${GIT_AUTHOR_NAME}
  else
    git config user.name
  fi
}

function _author_email() {
  if [ -n "${GIT_AUTHOR_EMAIL}" ]; then
    echo ${GIT_AUTHOR_EMAIL}
  else
    git config user.email
  fi
}

function _committer_name() {
  if [ -n "${GIT_COMMITTER_NAME}" ]; then
    echo ${GIT_COMMITTER_NAME}
  else
    git config user.name
  fi
}

function _committer_email() {
  if [ -n "${GIT_COMMITTER_EMAIL}" ]; then
    echo ${GIT_COMMITTER_EMAIL}
  else
    git config user.email
  fi
}

function _myenv() {
  echo "# Commit with following user."
  echo "#   Author: `_author_name` <`_author_email`>"
  echo "#   Commit: `_committer_name` <`_committer_email`>"
}

function _show_last_commit_msg() {
  echo "# Last commit message"
  echo "#   `git log -1 --oneline`"
}

if [ "$2" = "" ]; then
  mv $1 $1.tmp
  echo "" >> $1
  echo "`_myenv`" >> $1
  echo "" >> $1
  echo "`_show_last_commit_msg`" >> $1
  cat $1.tmp >> $1
  rm -f $1.tmp
fi
